### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jakobloekke** [aramk/meteor-collection-table#1]
This seems like a cool package!
It would be really nice with just a small code example of how to use it. :)

**Comment by aramk** [comment]
I really should at some point. I'll try to find some time to add a decent readme and some screenshots soon.

**Comment by kumarravigithub** [comment]
at least let us know how to begin. What to write after adding it to the meteor app.

**Comment by aramk** [comment]
Sorry for the delay. I've published 0.4.0 and added a proper readme and a link to the demo app at https://github.com/aramk/meteor-sandbox.
