### ISSUE TITLE
'meteor add' routine fails on LESS

### ISSUE THREAD

**Issue by tried2call** [aramk/meteor-collection-table#2]
Hello.
I'm installing meteor-collection-table on the current version V1.21 of Meteor, and it is failing on LESS.
Specifically: "error: Conflict: Constraint less@1.0.5 is not satisfied by less 2.5.1.

I installed less 2.5.1 separately after this error was reported, but didn't help.

Any ideas to fix this incompatibility ?  Much appreciated !

Paul J

**Comment by aramk** [comment]
You can try to set up a submodule and point it to the feature/meteor-1.2 branch. Some projects are still using the 1.1.0.3 so I've kept that around in the main branch.

**Comment by tried2call** [comment]
Thank you !

**Comment by croustibat65** [comment]
aramk, how do you suggest doing that?
By cloning your project (cheking out feature/meteor-1.2) inside our project's package folder?

**Comment by aramk** [comment]
Yep, at the moment I'm using submodules for any custom packages.
