### ISSUE TITLE
Does meteor-collection-table still work properly in the current version of Meteor ?

### ISSUE THREAD

**Issue by tried2call** [aramk/meteor-collection-table#3]
Hello Aram.
2 items:
- does collection table work in the current version of Meteor ?
- if yes, is there any other documentation available, or can i just use that for aslagle;ractive-tables ?
  Thanks !

tried2call

**Comment by aramk** [comment]
Hi. It works with Meteor 1.2.1 on this branch: https://github.com/aramk/meteor-collection-table/tree/feature/meteor-1.2. The docs are in the readme and `settings` accepts options passed to reactive-table.

**Comment by tried2call** [comment]
Thank you Aram !
